version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
      - javascript
    commit-message:
      prefix: ⬆️

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependencies
      - action
    commit-message:
      prefix: 👷
