version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    reviewers:
      - arelstone
    labels:
      - dependencies
      - javascript

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    reviewers:
      - arelstone
    labels:
      - dependencies
      - action